version: "3"
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  node:
    depends_on:
      - mysql_db
    build: .
    container_name: cons-node
    environment:
      - DATABASE=$DATABASE
      - USERNAMEDB=$USERNAMEDB
      - PASSWORD=$PASSWORD
      - HOST=$HOST
      - PORT=$PORTDB
      - DIALECT=$DIALECT
    ports:
      - 8080:8080
    networks:
      - node-network
    command: ["yarn", "start"]
volumes:
  mysql_db:
    driver: local
networks:
  node-network:
