# auth.swagger.yaml
paths:
  /auth/list:
    get:
      description: responses
      tags: [Auth]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              message:
                type: string
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
        '403':
          description: Forbidden
          schema:
            type: object
            properties:
              message:
                type: string
        '404':
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              message:
                type: string
  /auth/login:
    post:
      description: User login
      tags: [Auth]
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              pass_word:
                type: string
            example:
              email: fake@example.com
              pass_word: Password@1
          description: User credentials as a JSON object
      responses:
        '200':
          description: Login Successful
          schema:
            type: object
            properties:
              message:
                type: string
              token:
                type: string
        '400':
          description: Email or password is incorrect !
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: Internal server error !
          schema:
            type: object
            properties:
              message:
                type: string
  /auth/sign-up:
    post:
      description: User sign up
      tags: [Auth]
      responses:
        '200':
          description: Create user successful !
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Email already exits !
          schema:
            type: object
            properties:
              message:
                type: string
        '500':
          description: Internal server error !
          schema:
            type: object
            properties:
              message:
                type: string
